apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thrift-ingress
  namespace: thrift
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: thrift.local
    http:  
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: thrift-worker-service
            port:
              number: 80